spring:
  application:
    name: user-subscription-service
  liquibase:
    enabled: false
  datasource:
    url: jdbc:h2:mem:test_db
    driver-class-name: org.h2.Driver
    username: sa
    password: 123
  h2:
    console:
      enabled: true
      path: /h2-console
  jpa:
    database: h2
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: create
    show-sql: true